model:
  type: inf-llm
  path: mistralai/Mistral-7B-Instruct-v0.2
  # block_size: 128
  block_size: 4
  n_init: 2
  n_local: 8
  topk: 16
  repr_topk: 4
  max_cached_block: 32
  exc_block_size: 8
  fattn: false
  base: 1000000
  distance_scale: 1.0

max_len: 2147483647
# chunk_size: 8192
chunk_size: 16
conv_type: mistral-inst